'use strict';

/**
 * Visual assembly — ALL through Canva (Agent 4 — autonomous posting).
 *
 * 🔴 Owner directive: visuals are built ONLY through Canva (brand templates +
 *    brand kit), never hand-composed.
 *
 * Two backends:
 *  - AGENT (Pro, default): the bot uploads photos as Canva assets via REST, then
 *    a headless Claude "designer" (agent.js) copies the brand carousel template
 *    and update_fills the photos + text via the Canva MCP — the flow proven to
 *    work on Pro. (Autofill REST is Enterprise-only.)
 *  - AUTOFILL (Enterprise): assembleCarouselAutofill() kept for if/when the
 *    account is Enterprise (cheaper, no agent cost).
 *
 * Returns slides with BOTH a public export URL (for Metricool) and a buffer (for
 * verify.js). Copy (caption/headlines/body) is generated by Opus on the bot side
 * and passed in — the agent only PLACES it.
 */

const fs = require('fs');
const path = require('path');
const canva = require('./canva');
const agent = require('./agent');
const crop = require('./crop');
const yandex = require('./yandex');
const photosLib = require('./photos');
const { generateContent } = require('./generate');
const { createLogger } = require('../../shared/logger');

const logger = createLogger('content-bot');

const TEMPLATES_PATH = path.join(__dirname, '../../data/canva-templates.json');

function loadTemplates() {
  try {
    return JSON.parse(fs.readFileSync(TEMPLATES_PATH, 'utf8'));
  } catch {
    throw new Error('canva-templates.json missing — copy canva-templates.example.json to data/canva-templates.json and set carousel.templateDesignId');
  }
}

// Agent path needs: Canva REST (asset upload) + a configured carousel template id.
function isConfigured() {
  if (!canva.isConfigured()) return false;
  try {
    const t = loadTemplates();
    return !!(t.carousel && t.carousel.templateDesignId && !/^PASTE_/.test(t.carousel.templateDesignId));
  } catch { return false; }
}

async function fetchBuffer(url) {
  // Canva export URLs are short-lived/CDN-flaky — retry a few times before failing
  // so a transient 403/5xx doesn't sink the whole post.
  let lastErr;
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      const res = await fetch(url);
      if (res.ok) return Buffer.from(await res.arrayBuffer());
      lastErr = new Error(`canva export download ${res.status}`);
      if (res.status !== 403 && res.status < 500) break; // only retry 403 / 5xx
    } catch (err) { lastErr = err; }
    await new Promise((r) => setTimeout(r, 800 * attempt));
  }
  throw lastErr || new Error('canva export download failed');
}

/**
 * Assemble a carousel POST via the headless designer agent.
 * @param {object} p
 * @param {string} p.topic
 * @param {Array<{buffer:Buffer,name?:string}>} p.photos  ordered (slide 1 = cover)
 * @param {object} p.cover  { headline, cta }
 * @param {Array<{headline:string,body:string}>} p.inner  slides 2..n
 * @param {string} [p.caption]  override; otherwise generated by Opus
 * @returns {Promise<{caption, slides:Array<{url,buffer,alt}>, costUsd, overBudget}>}
 */
async function assembleCarousel({ topic, photos, cover, inner, caption, backups }) {
  if (!isConfigured()) throw new Error('Canva agent pipeline not configured (canva auth + carousel.templateDesignId in canva-templates.json)');
  if (!photos || photos.length < 1) throw new Error('assembleCarousel: need at least the cover photo');

  const cfg = loadTemplates().carousel;
  const templateDesignId = cfg.templateDesignId;
  const pageMap = cfg.pages || {};
  const els = (page) => {
    const e = pageMap[String(page)];
    if (!e || !e.bg || !e.headline) throw new Error(`canva-templates.json: missing element ids for page ${page}`);
    return e;
  };

  // 1) Pre-crop each photo to an exact 4:5 frame that CONTAINS the subject's
  //    whole body, then upload as a Canva asset. If the body can't fit the 4:5
  //    window (covered=false), swap in a backup photo rather than ship an
  //    amputated crop (owner rule 2026-07-03). Canva then fills a 4:5 element
  //    with a 4:5 image, so it has nothing left to cut.
  const pool = [...(backups || [])];
  const assetIds = [];
  for (let i = 0; i < photos.length; i++) {
    let current = photos[i];
    let result = null;
    for (;;) {
      try { result = await crop.safeCrop45(current.buffer); }
      catch (err) {
        logger.warn({ err: err.message, photo: current.name }, 'pre-crop failed → using original');
        result = { buffer: current.buffer, covered: true };
      }
      if (result.covered && !(result.cut = await crop.checkCropCut(result.buffer))) break;
      if (!pool.length) break;
      // не вставляем кадр, почти совпадающий с фото на других слайдах
      const usedElsewhere = photos.filter((p, j) => j !== i && p && p.path).map((p) => p.path);
      let altIdx = pool.findIndex((b) => !photosLib.nearDuplicate(b.path, usedElsewhere));
      if (altIdx < 0) altIdx = 0; // все кандидаты похожи — берём первый (лучше, чем резать тело)
      const alt = pool.splice(altIdx, 1)[0];
      try {
        const buffer = await yandex.downloadBuffer(alt.path);
        logger.info({ dropped: current.name, swappedIn: alt.name }, 'crop cannot fit whole body → swapping to backup photo');
        current = { buffer, name: alt.name, path: alt.path };
      } catch (err) { logger.warn({ err: err.message, backup: alt.name }, 'backup download failed'); }
    }
    if (!result.covered || result.cut) logger.warn({ photo: current.name, cut: !!result.cut }, 'no backup fits either → best-effort crop');
    photos[i] = current; // callers read photos[i].path for publish-time burn
    assetIds.push(await canva.uploadAsset(result.buffer, current.name || `photo-${i + 1}.jpg`));
  }

  // 2) Build the slide spec with EXACT element ids: page 1 = cover, 2..n = inner.
  const slidesSpec = [{ page: 1, assetId: assetIds[0], headline: cover.headline, cta: cover.cta, elements: els(1) }];
  for (let i = 0; i < inner.length; i++) {
    const page = i + 2;
    slidesSpec.push({
      page,
      assetId: assetIds[i + 1] || assetIds[assetIds.length - 1],
      headline: inner[i].headline,
      body: inner[i].body,
      elements: els(page),
    });
  }

  // 3) Delegate the Canva editing to the headless agent.
  const built = await agent.buildCarousel({ templateDesignId, slides: slidesSpec });
  if (!built.ok) throw new Error(`designer agent: ${built.error} (cost $${built.costUsd})`);

  // 4) Map agent slides (by page) back to texts + fetch buffers for verify.
  const byPage = new Map(built.slides.map((s) => [s.page, s.url]));
  const slides = [];
  for (const spec of slidesSpec) {
    const url = byPage.get(spec.page);
    if (!url) throw new Error(`designer agent: missing export for page ${spec.page}`);
    // page + bgElementId let the caller re-fill ONE slide's photo later
    // (targeted fix) without rebuilding the whole design.
    slides.push({ url, buffer: await fetchBuffer(url), alt: `${spec.headline} — AcroGym`, page: spec.page, bgElementId: spec.elements.bg });
  }

  const cap = caption || await generateContent('post', topic);
  return { caption: cap, slides, designId: built.designId, costUsd: built.costUsd, overBudget: built.overBudget };
}

/**
 * Replace ONE slide's background photo in an EXISTING design and re-export that
 * page (owner rule 2026-07-03: when verification flags a specific photo, swap
 * just that photo — don't rebuild the whole carousel). Tries candidates until
 * one crops with the whole body in frame and the design update sticks.
 * @returns {Promise<{url, buffer, name, path, costUsd}|null>}
 */
async function replaceSlidePhoto({ designId, page, bgElementId, candidates = [] }) {
  for (const cand of candidates) {
    let buffer;
    try { buffer = cand.buffer || await yandex.downloadBuffer(cand.path); }
    catch (err) { logger.warn({ err: err.message, photo: cand.name }, 'slide-fix: candidate download failed'); continue; }
    let cropped;
    try { cropped = await crop.safeCrop45(buffer); }
    catch (err) { logger.warn({ err: err.message, photo: cand.name }, 'slide-fix: crop failed'); continue; }
    if (!cropped.covered) { logger.info({ photo: cand.name }, 'slide-fix: body does not fit 4:5 → next candidate'); continue; }
    if (await crop.checkCropCut(cropped.buffer)) { logger.info({ photo: cand.name }, 'slide-fix: crop cut-check failed → next candidate'); continue; }
    const assetId = await canva.uploadAsset(cropped.buffer, cand.name || 'fix.jpg');
    const upd = await agent.updateFill({ designId, elementId: bgElementId, assetId });
    if (!upd.ok) { logger.warn({ err: upd.error, photo: cand.name }, 'slide-fix: update_fill failed'); continue; }
    const urls = await canva.exportDesign(designId, 'png');
    const url = urls[page - 1];
    if (!url) continue;
    logger.info({ page, photo: cand.name, costUsd: upd.costUsd }, 'slide-fix: photo replaced in design');
    return { url, buffer: await fetchBuffer(url), name: cand.name, path: cand.path, costUsd: upd.costUsd || 0 };
  }
  return null;
}

/**
 * Assemble a single 9:16 Instagram STORY via the headless designer agent.
 * @param {object} p
 * @param {string} p.topic
 * @param {{buffer:Buffer,name?:string}} p.photo
 * @param {string} p.headline
 * @param {string} [p.cta]
 * @param {string} p.caption
 * @returns {Promise<{caption, slides:Array<{url,buffer,alt}>, costUsd, overBudget}>}
 */
// Build ONE on-brand 9:16 frame (full-bleed photo + Gerhaus headline + asterisk
// + CTA) via the story template. Shared by stories AND reels (reels animate it).
async function buildStoryFrame({ photo, headline, cta }) {
  const cfg = loadTemplates().story;
  if (!cfg || !cfg.templateDesignId || !cfg.elements || !cfg.elements.bg || !cfg.elements.headline) {
    throw new Error('canva-templates.json: missing story template (story.templateDesignId + elements.bg/headline)');
  }
  if (!photo || !photo.buffer) throw new Error('buildStoryFrame: need a photo');

  // Pre-crop to an exact 9:16 frame so Canva fills a full-bleed 1080x1920 bg.
  let buf = photo.buffer;
  try {
    const r = await crop.safeCrop916(buf);
    buf = r.buffer;
    if (!r.covered) logger.warn({ photo: photo.name }, 'story crop cannot fit whole body → best effort');
  } catch (err) { logger.warn({ err: err.message, photo: photo.name }, 'story pre-crop failed → using original'); }
  const assetId = await canva.uploadAsset(buf, photo.name || 'story.jpg');

  const built = await agent.buildStory({
    templateDesignId: cfg.templateDesignId, assetId, elements: cfg.elements, headline, cta,
  });
  if (!built.ok) throw new Error(`story agent: ${built.error} (cost $${built.costUsd})`);
  return { url: built.url, buffer: await fetchBuffer(built.url), costUsd: built.costUsd, overBudget: built.overBudget };
}

async function assembleStory({ topic, photo, headline, cta, caption }) {
  const frame = await buildStoryFrame({ photo, headline, cta });
  const slide = { url: frame.url, buffer: frame.buffer, alt: `${headline} — AcroGym` };
  const cap = caption || await generateContent('post', topic);
  return { caption: cap, slides: [slide], costUsd: frame.costUsd, overBudget: frame.overBudget };
}

/**
 * Assemble a 9:16 REEL: build the branded frame, then add gentle Ken-Burns motion
 * (ffmpeg) → MP4. The MP4 is a local buffer (no public URL — delivered to the
 * owner; auto-publish needs hosting). Returns the still PNG too (card thumbnail).
 */
async function assembleReel({ topic, photo, headline, cta, caption, seconds }) {
  const video = require('./video');
  const frame = await buildStoryFrame({ photo, headline, cta });
  const mp4 = await video.kenBurnsReel(frame.buffer, seconds ? { seconds } : {});
  const cap = caption || await generateContent('post', topic);
  return {
    caption: cap,
    slides: [{ buffer: mp4, isVideo: true, poster: frame.buffer, alt: `${headline} — AcroGym` }],
    costUsd: frame.costUsd, overBudget: frame.overBudget,
  };
}

module.exports = { isConfigured, loadTemplates, assembleCarousel, assembleStory, assembleReel, buildStoryFrame, replaceSlidePhoto, TEMPLATES_PATH };
