'use strict';

/**
 * Visual assembly — ALL through Canva (Agent 4 — autonomous posting).
 *
 * 🔴 Owner directive: visuals are built ONLY through Canva (brand templates +
 *    brand kit), never hand-composed.
 *
 * Two backends:
 *  - AGENT (Pro, default): the bot uploads photos as Canva assets via REST, then
 *    a headless Claude "designer" (agent.js) copies the brand carousel template
 *    and update_fills the photos + text via the Canva MCP — the flow proven to
 *    work on Pro. (Autofill REST is Enterprise-only.)
 *  - AUTOFILL (Enterprise): assembleCarouselAutofill() kept for if/when the
 *    account is Enterprise (cheaper, no agent cost).
 *
 * Returns slides with BOTH a public export URL (for Metricool) and a buffer (for
 * verify.js). Copy (caption/headlines/body) is generated by Opus on the bot side
 * and passed in — the agent only PLACES it.
 */

const fs = require('fs');
const path = require('path');
const canva = require('./canva');
const agent = require('./agent');
const crop = require('./crop');
const { generateContent } = require('./generate');
const { createLogger } = require('../../shared/logger');

const logger = createLogger('content-bot');

const TEMPLATES_PATH = path.join(__dirname, '../../data/canva-templates.json');

function loadTemplates() {
  try {
    return JSON.parse(fs.readFileSync(TEMPLATES_PATH, 'utf8'));
  } catch {
    throw new Error('canva-templates.json missing — copy canva-templates.example.json to data/canva-templates.json and set carousel.templateDesignId');
  }
}

// Agent path needs: Canva REST (asset upload) + a configured carousel template id.
function isConfigured() {
  if (!canva.isConfigured()) return false;
  try {
    const t = loadTemplates();
    return !!(t.carousel && t.carousel.templateDesignId && !/^PASTE_/.test(t.carousel.templateDesignId));
  } catch { return false; }
}

async function fetchBuffer(url) {
  // Canva export URLs are short-lived/CDN-flaky — retry a few times before failing
  // so a transient 403/5xx doesn't sink the whole post.
  let lastErr;
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      const res = await fetch(url);
      if (res.ok) return Buffer.from(await res.arrayBuffer());
      lastErr = new Error(`canva export download ${res.status}`);
      if (res.status !== 403 && res.status < 500) break; // only retry 403 / 5xx
    } catch (err) { lastErr = err; }
    await new Promise((r) => setTimeout(r, 800 * attempt));
  }
  throw lastErr || new Error('canva export download failed');
}

/**
 * Assemble a carousel POST via the headless designer agent.
 * @param {object} p
 * @param {string} p.topic
 * @param {Array<{buffer:Buffer,name?:string}>} p.photos  ordered (slide 1 = cover)
 * @param {object} p.cover  { headline, cta }
 * @param {Array<{headline:string,body:string}>} p.inner  slides 2..n
 * @param {string} [p.caption]  override; otherwise generated by Opus
 * @returns {Promise<{caption, slides:Array<{url,buffer,alt}>, costUsd, overBudget}>}
 */
async function assembleCarousel({ topic, photos, cover, inner, caption }) {
  if (!isConfigured()) throw new Error('Canva agent pipeline not configured (canva auth + carousel.templateDesignId in canva-templates.json)');
  if (!photos || photos.length < 1) throw new Error('assembleCarousel: need at least the cover photo');

  const cfg = loadTemplates().carousel;
  const templateDesignId = cfg.templateDesignId;
  const pageMap = cfg.pages || {};
  const els = (page) => {
    const e = pageMap[String(page)];
    if (!e || !e.bg || !e.headline) throw new Error(`canva-templates.json: missing element ids for page ${page}`);
    return e;
  };

  // 1) Pre-crop each photo to an exact 4:5 frame CENTRED on the people, then
  //    upload as a Canva asset. Canva now fills a 4:5 element with a 4:5 image,
  //    so it can't re-crop and cut faces — the framing is controlled here.
  const assetIds = [];
  for (let i = 0; i < photos.length; i++) {
    let buf = photos[i].buffer;
    try { buf = await crop.safeCrop45(buf); }
    catch (err) { logger.warn({ err: err.message, photo: photos[i].name }, 'pre-crop failed → using original'); }
    assetIds.push(await canva.uploadAsset(buf, photos[i].name || `photo-${i + 1}.jpg`));
  }

  // 2) Build the slide spec with EXACT element ids: page 1 = cover, 2..n = inner.
  const slidesSpec = [{ page: 1, assetId: assetIds[0], headline: cover.headline, cta: cover.cta, elements: els(1) }];
  for (let i = 0; i < inner.length; i++) {
    const page = i + 2;
    slidesSpec.push({
      page,
      assetId: assetIds[i + 1] || assetIds[assetIds.length - 1],
      headline: inner[i].headline,
      body: inner[i].body,
      elements: els(page),
    });
  }

  // 3) Delegate the Canva editing to the headless agent.
  const built = await agent.buildCarousel({ templateDesignId, slides: slidesSpec });
  if (!built.ok) throw new Error(`designer agent: ${built.error} (cost $${built.costUsd})`);

  // 4) Map agent slides (by page) back to texts + fetch buffers for verify.
  const byPage = new Map(built.slides.map((s) => [s.page, s.url]));
  const slides = [];
  for (const spec of slidesSpec) {
    const url = byPage.get(spec.page);
    if (!url) throw new Error(`designer agent: missing export for page ${spec.page}`);
    slides.push({ url, buffer: await fetchBuffer(url), alt: `${spec.headline} — AcroGym` });
  }

  const cap = caption || await generateContent('post', topic);
  return { caption: cap, slides, costUsd: built.costUsd, overBudget: built.overBudget };
}

module.exports = { isConfigured, loadTemplates, assembleCarousel, TEMPLATES_PATH };
