'use strict';

/**
 * Content calendar + scheduler (Agent 4 — autonomous posting, Phase 3).
 *
 * Two entry paths, both ending in the publish.js hybrid gate:
 *   - SCHEDULED (cron): routine themes (e.g. weekly recap). routine=true → may
 *     auto-publish after self-verification.
 *   - ON-DEMAND (/post <topic>): routine=false → always an approval card.
 *
 * Visuals are assembled ONLY through Canva (assemble.js). Photos come from
 * Yandex.Disk /AcroGym/Marketing. Slide copy is generated by Claude as strict
 * JSON so the cover + inner slides are filled deterministically.
 */

const cron = require('node-cron');
const yandex = require('./yandex');
const photos = require('./photos');
const assemble = require('./assemble');
const agent = require('./agent');
const publish = require('./publish');
const { verifyCarousel, verifyCaption } = require('./verify');
const { generateText } = require('../../shared/claude');
const { createLogger } = require('../../shared/logger');

const logger = createLogger('content-bot');

const TZ = process.env.TIMEZONE || 'Asia/Qatar';

// Routine themes that may auto-publish. Cron in brand timezone.
// Conservative default: one weekly recap. Easy to extend.
// 🔴 routine=false EVERYWHERE until the visual pipeline is reliable (2026-06-28:
// agent filled the wrong layer → split photos; verify missed it). NOTHING
// auto-publishes — every scheduled build still goes to the owner for ✅.
const PLAN = [
  { name: 'weekly-recap', cron: '0 18 * * 4', theme: 'Weekly recap: highlights from training this week at AcroGym', slides: 4, routine: false },
];

const PLAN_SYSTEM = `You write Instagram carousel copy for AcroGym Qatar — a kids' gymnastics & acrobatics club in Doha. Audience: parents of children 3–14. Voice: warm, energetic, safe, professional. Output language: ENGLISH only.
Given a THEME and a slide count N, return STRICT JSON (no prose):
{"cover":{"headline":"<1-2 SHORT words only, ≤14 characters total — it must fit one line>","cta":"<short CTA, e.g. BOOK A TRIAL>"},
 "inner":[{"headline":"<ONE short word, uppercase, ≤11 chars>","body":"<1-2 sentences, <140 chars>"}, ... exactly N-1 items],
 "caption":"<full IG caption with 1-2 emojis and 6-8 relevant hashtags>"}
Keep it child-safe and on-brand. Never invent specific results or medical claims.`;

function parseJson(text) {
  try { const m = String(text).match(/\{[\s\S]*\}/); return m ? JSON.parse(m[0]) : null; } catch { return null; }
}

// Generate slide copy for a theme.
async function generatePlan(theme, slides = 4) {
  const raw = await generateText({
    system: PLAN_SYSTEM,
    user: `THEME: ${theme}\nN: ${slides}\nReturn the JSON.`,
    maxTokens: 900,
  });
  const plan = parseJson(raw);
  if (!plan || !plan.cover || !Array.isArray(plan.inner)) {
    throw new Error('plan generation: unparseable copy');
  }
  return plan;
}

// Pick N photos from Marketing (prefer a content folder, fall back to root).
async function pickPhotos(n, folder) {
  const candidates = [];
  const tryFolders = [folder, '/AcroGym/Marketing/AcroGym Competiton 2026', yandex.MARKETING].filter(Boolean);
  for (const f of tryFolders) {
    try {
      const imgs = await yandex.listImages(f, { limit: 200 });
      if (imgs.length) { candidates.push(...imgs); break; }
    } catch (err) { logger.warn({ folder: f, err: err.message }, 'pickPhotos: folder skip'); }
  }
  if (!candidates.length) throw new Error('no images found under /AcroGym/Marketing');
  // Shuffle then take n (deterministic enough; avoids always the same shots).
  for (let i = candidates.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [candidates[i], candidates[j]] = [candidates[j], candidates[i]]; }
  const chosen = candidates.slice(0, n);
  const photos = [];
  for (const c of chosen) {
    photos.push({ buffer: await yandex.downloadBuffer(c.path), name: c.name });
  }
  return photos;
}

/**
 * Build a themed carousel end-to-end and route it through the gate.
 * @param {object} bot Telegram bot
 * @param {string|number} ownerChatId
 * @param {object} opts { theme, slides, routine, folder }
 */
async function buildAndRoute(bot, ownerChatId, { theme, slides = 4, routine = false, folder } = {}) {
  logger.info({ theme, slides, routine }, 'calendar: building carousel');
  const plan = await generatePlan(theme, slides);
  const sel = await photos.selectBest(slides, { folder });

  const assembled = await assemble.assembleCarousel({
    topic: theme,
    photos: sel.photos,
    cover: { headline: plan.cover.headline, cta: plan.cover.cta },
    inner: plan.inner,
    caption: plan.caption,
  });

  // Self-verify EVERYTHING before it can be shown or auto-published:
  // every slide (structure/integrity/visual), carousel-level consistency, and
  // the caption.
  const buffers = assembled.slides.map((s) => s.buffer).filter(Boolean);
  const vr = await verifyCarousel(buffers, { context: `AcroGym ${theme}` });
  const cap = verifyCaption(assembled.caption);

  const issues = [
    ...vr.slides.flatMap((s, i) => s.issues.map((x) => `s${i + 1}:${x}`)),
    ...vr.carousel.map((x) => `carousel:${x}`),
    ...cap.issues.map((x) => `caption:${x}`),
  ];
  if (assembled.overBudget) issues.push(`cost:over budget ($${(assembled.costUsd || 0).toFixed(2)})`);
  const verifyOk = vr.ok && cap.ok;

  const cost = typeof assembled.costUsd === 'number' ? ` · $${assembled.costUsd.toFixed(2)}` : '';
  const draft = publish.newDraft({
    kind: 'post', igType: 'POST',
    caption: assembled.caption,
    slides: assembled.slides,
    theme, slidesCount: slides, // kept so 🔄 Rebuild can repeat the same brief
    // Over-budget runs never auto-publish — route to manual review.
    routine: routine && verifyOk && !assembled.overBudget,
    verify: { ok: verifyOk && !assembled.overBudget, issues },
    source: `${routine ? 'calendar' : 'on-demand'}: ${theme}${cost}`,
  });

  if (assembled.overBudget) {
    await bot.sendMessage(ownerChatId,
      `⚠️ Пост собрался дороже лимита ($${(assembled.costUsd || 0).toFixed(2)} > $${agent.MAX_COST_USD}). Автопост отключён — проверь вручную.`).catch(() => {});
  }

  return publish.route(bot, ownerChatId, draft);
}

/** Start the cron schedules. Call once from index.js after the bot is up. */
function start(bot, ownerChatId) {
  const jobs = [];
  for (const item of PLAN) {
    const job = cron.schedule(item.cron, async () => {
      try {
        await buildAndRoute(bot, ownerChatId, { theme: item.theme, slides: item.slides, routine: item.routine });
      } catch (err) {
        logger.error({ err: err.message, name: item.name }, 'calendar job failed');
        await bot.sendMessage(ownerChatId, `⚠️ Автопост «${item.name}» не собрался: ${err.message}`).catch(() => {});
      }
    }, { timezone: TZ });
    jobs.push(job);
    logger.info({ name: item.name, cron: item.cron }, 'calendar job scheduled');
  }
  return jobs;
}

module.exports = { start, buildAndRoute, generatePlan, pickPhotos, PLAN };
