'use strict';

/**
 * Content calendar + scheduler (Agent 4 — autonomous posting, Phase 3).
 *
 * Two entry paths, both ending in the publish.js hybrid gate:
 *   - SCHEDULED (cron): routine themes (e.g. weekly recap). routine=true → may
 *     auto-publish after self-verification.
 *   - ON-DEMAND (/post <topic>): routine=false → always an approval card.
 *
 * Visuals are assembled ONLY through Canva (assemble.js). Photos come from
 * Yandex.Disk /AcroGym/Marketing. Slide copy is generated by Claude as strict
 * JSON so the cover + inner slides are filled deterministically.
 */

const cron = require('node-cron');
const yandex = require('./yandex');
const photos = require('./photos');
const plan = require('./plan');
const research = require('./research');
const { getPreferredLanguage } = require('../../shared/preferences');
const assemble = require('./assemble');
const agent = require('./agent');
const publish = require('./publish');
const { verifyCarousel, verifySlide, verifyCaption } = require('./verify');
const { generateText, beginCost, endCost } = require('./llm');
const { createLogger } = require('../../shared/logger');

const logger = createLogger('content-bot');

const TZ = process.env.TIMEZONE || 'Asia/Qatar';

// Routine themes that may auto-publish. Cron in brand timezone.
// Conservative default: one weekly recap. Easy to extend.
// 🔴 routine=false EVERYWHERE until the visual pipeline is reliable (2026-06-28:
// agent filled the wrong layer → split photos; verify missed it). NOTHING
// auto-publishes — every scheduled build still goes to the owner for ✅.
const PLAN = [
  { name: 'weekly-recap', cron: '0 18 * * 4', theme: 'Weekly recap: highlights from training this week at AcroGym', slides: 4, routine: false },
];

const PLAN_SYSTEM = `You write Instagram carousel copy for AcroGym Qatar — a kids' gymnastics & acrobatics club in Doha. Audience: parents of children 3–14. Voice: warm, energetic, safe, professional. Output language: ENGLISH only — the THEME may be written in Russian or any language, but ALWAYS write every headline, body and caption in ENGLISH (this is published copy for the audience).
Given a THEME and a slide count N, return STRICT JSON (no prose):
{"cover":{"headline":"<1-2 SHORT words only, ≤14 characters total — it must fit one line>","cta":"<short CTA, e.g. BOOK YOUR FIRST CLASS>"},
 "inner":[{"headline":"<ONE short word, uppercase, ≤11 chars>","body":"<1-2 sentences, <140 chars>"}, ... exactly N-1 items],
 "caption":"<full IG caption with 1-2 emojis and 6-8 relevant hashtags>"}
If a PHOTOS block is provided (a short description of the REAL photo used on each slide: 1 = cover, then inner slides in order), write each slide's copy to MATCH its actual photo — never describe an action, apparatus or setting that is not in that photo's description.
Keep it child-safe and on-brand. NEVER use the words "trial" or "free" anywhere (the first class is paid): the standard CTA is "BOOK YOUR FIRST CLASS". Never invent specific results or medical claims.`;

function parseJson(text) {
  try { const m = String(text).match(/\{[\s\S]*\}/); return m ? JSON.parse(m[0]) : null; } catch { return null; }
}

// Generate slide copy for a theme.
async function generatePlan(theme, slides = 4, photoNotes = null) {
  const photosBlock = photoNotes && photoNotes.some(Boolean)
    ? `PHOTOS:\n${photoNotes.map((n, i) => `${i + 1}${i === 0 ? ' (cover)' : ''}: ${n || '(no description)'}`).join('\n')}\n`
    : '';
  const raw = await generateText({
    system: PLAN_SYSTEM,
    user: `THEME: ${theme}\nN: ${slides}\n${photosBlock}Return the JSON.`,
    maxTokens: 900,
  });
  const plan = parseJson(raw);
  if (!plan || !plan.cover || !Array.isArray(plan.inner)) {
    throw new Error('plan generation: unparseable copy');
  }
  // Защита от срыва инструкции LLM: контракт — обложка + (N-1) внутренних = N
  // страниц, но модель иногда возвращает N внутренних → сборка запрашивает
  // несуществующую страницу N+1 в шаблоне Canva («missing element ids for page 5»).
  // Жёстко режем inner до N-1, чтобы всего было не больше N страниц.
  const maxInner = Math.max(1, slides - 1);
  if (plan.inner.length > maxInner) {
    logger.warn({ got: plan.inner.length, keep: maxInner, slides }, 'plan: LLM вернул лишние inner-слайды — обрезаю до N-1');
    plan.inner = plan.inner.slice(0, maxInner);
  }
  return plan;
}

// Pick N photos from Marketing (prefer a content folder, fall back to root).
async function pickPhotos(n, folder) {
  const candidates = [];
  const tryFolders = [folder, '/AcroGym/Marketing/AcroGym Competiton 2026', yandex.MARKETING].filter(Boolean);
  for (const f of tryFolders) {
    try {
      const imgs = await yandex.listImages(f, { limit: 200 });
      if (imgs.length) { candidates.push(...imgs); break; }
    } catch (err) { logger.warn({ folder: f, err: err.message }, 'pickPhotos: folder skip'); }
  }
  if (!candidates.length) throw new Error('no images found under /AcroGym/Marketing');
  // Shuffle then take n (deterministic enough; avoids always the same shots).
  for (let i = candidates.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [candidates[i], candidates[j]] = [candidates[j], candidates[i]]; }
  const chosen = candidates.slice(0, n);
  const photos = [];
  for (const c of chosen) {
    photos.push({ buffer: await yandex.downloadBuffer(c.path), name: c.name });
  }
  return photos;
}

// Copy for a single Instagram STORY (9:16): short headline + CTA + caption.
const STORY_SYSTEM = `You write copy for ONE Instagram STORY (9:16 vertical) for AcroGym Qatar — a kids' gymnastics & acrobatics club in Doha. Audience: parents of children 3–14. English only — the TOPIC may be written in Russian or any language, but ALWAYS write the headline, CTA and caption in ENGLISH (this is published copy for the audience). Voice: warm, energetic, safe. NEVER use the words "trial" or "free" anywhere (the first class is paid): the standard CTA is "BOOK YOUR FIRST CLASS". 
Given a TOPIC, return STRICT JSON (no prose):
{"headline":"<1-2 SHORT punchy words, ≤12 characters total, MUST fit one line — e.g. \\"WE'RE OPEN\\", \\"NEW GYM\\", \\"SOON\\">","cta":"<short CTA, e.g. BOOK YOUR FIRST CLASS>","caption":"<short IG caption, 1-2 emojis, 3-6 hashtags>"}
Keep it child-safe and on-brand. Never invent prices, dates, or results.`;

async function generateStoryCopy(theme) {
  const raw = await generateText({ system: STORY_SYSTEM, user: `TOPIC: ${theme}\nReturn the JSON.`, maxTokens: 400 });
  const c = parseJson(raw);
  if (!c || !c.headline) throw new Error('story copy: unparseable');
  return { headline: c.headline, cta: c.cta || 'BOOK YOUR FIRST CLASS', caption: c.caption || '' };
}

/**
 * Build a single 9:16 STORY end-to-end and route it through the gate.
 * Mirrors buildAndRoute (auto-fix attempts, true cost, approval card) for stories.
 */
async function buildStoryAndRoute(bot, ownerChatId, { theme, routine = false, folder } = {}) {
  const MAX_ATTEMPTS = Math.max(1, parseInt(process.env.CONTENT_BUILD_ATTEMPTS || '2', 10));
  logger.info({ theme, routine, maxAttempts: MAX_ATTEMPTS }, 'calendar: building story');

  let totalCost = 0; let best = null; const exclude = [];
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const scope = beginCost();
    const copy = await generateStoryCopy(theme);
    const sel = await photos.selectBest(1, { folder, topic: theme, exclude, story: true });
    (sel.ranked || []).forEach((p) => exclude.push(p));
    const photo = sel.photos && sel.photos[0];
    if (!photo) throw new Error('story: no photo selected');
    const assembled = await assemble.assembleStory({ topic: theme, photo, headline: copy.headline, cta: copy.cta, caption: copy.caption });
    const buf = assembled.slides[0] && assembled.slides[0].buffer;
    const vr = buf
      ? await verifySlide(buf, {
          context: 'AcroGym kids gymnastics & acrobatics — single Instagram story 9:16 (cover-style: hook headline + asterisk + CTA pill)',
          expectedRatio: 1080 / 1920, ratioLabel: '9:16',
        })
      : { ok: false, issues: ['нет изображения сторис'] };
    const cap = verifyCaption(assembled.caption);
    const apiCost = endCost(scope);
    totalCost += apiCost + (assembled.costUsd || 0);

    const issues = [...vr.issues.map((x) => `сторис: ${x}`), ...cap.issues.map((x) => `подпись: ${x}`)];
    if (assembled.overBudget) issues.push(`стоимость: дороже лимита ($${(assembled.costUsd || 0).toFixed(2)})`);
    const verifyOk = vr.ok && cap.ok && !assembled.overBudget;
    const cand = { assembled, issues, verifyOk, photoPaths: [photo.path] };
    if (verifyOk) { best = cand; logger.info({ attempt }, 'story self-check passed'); break; }
    if (!best || issues.length < best.issues.length) best = cand;
    logger.warn({ attempt, issueCount: issues.length }, 'story self-check found issues');
    if (attempt < MAX_ATTEMPTS) {
      await bot.sendMessage(ownerChatId, `🔍 Проверка нашла замечания по сторис — пересобираю на другом фото (попытка ${attempt + 1}/${MAX_ATTEMPTS})…`).catch(() => {});
    }
  }

  const { assembled, issues, verifyOk, photoPaths } = best;
  const draft = publish.newDraft({
    kind: 'story', igType: 'STORY',
    caption: assembled.caption, slides: assembled.slides,
    theme, slidesCount: 1, storyFormat: true,
    photoPaths,                 // burned (recorded as used) only on actual publish
    routine: routine && verifyOk,
    verify: { ok: verifyOk, issues },
    costUsd: totalCost,
    source: `${routine ? 'calendar' : 'on-demand'} story: ${theme}`,
  });
  return publish.route(bot, ownerChatId, draft);
}

/**
 * Build a 9:16 REEL (branded frame + gentle Ken-Burns motion → MP4) and deliver
 * it to the owner as a Telegram video. 🔴 Reels are NOT auto-published yet: the
 * MP4 is generated locally (no public URL for Metricool), so for now it's a
 * preview the owner downloads/posts. Auto-publish needs a hosting decision.
 */
// Reels are built from REAL video clips the owner drops in /Marketing/Videos —
// NOT Ken-Burns from a still. We pick a clip, clean it to an IG-ready 9:16 mp4,
// caption it (English), host it, and route through the approval gate.
const REEL_RECENT = []; // last few clip paths used — avoid repeating the same clip
async function buildReelAndRoute(bot, ownerChatId, { theme, routine = false, folder } = {}) {
  const video = require('./video');
  const os = require('os'); const fssync = require('fs'); const pathMod = require('path');
  logger.info({ theme }, 'calendar: building reel (real clip)');
  const scope = beginCost();

  // 1. pick a real clip (prefer ones not used recently).
  const vids = await yandex.listVideos(folder || yandex.VIDEOS);
  if (!vids.length) throw new Error('reel: нет видео в /AcroGym/Marketing/Videos — закинь клипы туда');
  const fresh = vids.filter((v) => !REEL_RECENT.includes(v.path));
  const pool = fresh.length ? fresh : vids;
  const pick = pool[Math.floor(Math.random() * pool.length)];
  REEL_RECENT.push(pick.path); while (REEL_RECENT.length > 5) REEL_RECENT.shift();

  // 2. download → clean transcode to IG-ready 9:16 mp4 (+ poster frame).
  const srcBuf = await yandex.downloadBuffer(pick.path);
  const tmp = fssync.mkdtempSync(pathMod.join(os.tmpdir(), 'reelsrc-'));
  const ext = (pick.name.match(/\.[a-z0-9]+$/i) || ['.mov'])[0];
  const inPath = pathMod.join(tmp, `in${ext}`);
  fssync.writeFileSync(inPath, srcBuf);
  let mp4; let poster;
  try {
    const out = await video.cleanReel(inPath, { maxSeconds: parseInt(process.env.CONTENT_REEL_MAX_SECONDS || '90', 10) });
    mp4 = out.buffer; poster = out.poster;
  } finally { try { fssync.rmSync(tmp, { recursive: true, force: true }); } catch { /* ignore */ } }

  // 3. caption (English brand voice).
  const copy = await generateStoryCopy(theme);
  const caption = (copy.caption && copy.caption.trim()) || copy.headline || `AcroGym — ${theme}`;

  // 4. verify the cover frame + host the MP4 on Yandex → public direct URL.
  const vr = poster
    ? await verifySlide(poster, { context: 'AcroGym reel 9:16 video frame (real footage, no overlaid text expected)', expectedRatio: 1080 / 1920, ratioLabel: '9:16' })
    : { ok: true, issues: [] };
  const cap = verifyCaption(caption);
  let mediaUrl = null; let hostErr = null;
  try {
    const up = await yandex.uploadPublic(mp4, `reel-${Date.now()}.mp4`, { contentType: 'video/mp4' });
    mediaUrl = up.directUrl;
  } catch (err) { hostErr = err.message; logger.error({ err: err.message }, 'reel hosting upload failed'); }

  const apiCost = endCost(scope);
  const issues = [...vr.issues.map((x) => `кадр: ${x}`), ...cap.issues.map((x) => `подпись: ${x}`)];
  if (hostErr) issues.push(`хостинг видео: ${hostErr}`);
  const verifyOk = vr.ok && cap.ok && !!mediaUrl;

  const draft = publish.newDraft({
    kind: 'reel', igType: 'REEL',
    caption,
    slides: [{ url: mediaUrl, buffer: mp4, poster, isVideo: true, alt: `AcroGym reel — ${theme}` }],
    theme, reelFormat: true,
    routine: routine && verifyOk,
    verify: { ok: verifyOk, issues },
    costUsd: apiCost,
    source: `${routine ? 'calendar' : 'on-demand'} reel(${pick.name}): ${theme}`,
  });
  return publish.route(bot, ownerChatId, draft);
}

/**
 * Build a themed carousel end-to-end and route it through the gate.
 * @param {object} bot Telegram bot
 * @param {string|number} ownerChatId
 * @param {object} opts { theme, slides, routine, folder }
 */
async function buildDraft(bot, ownerChatId, { theme, slides = 4, routine = false, folder, exclude = [], suppliedPhotos = null } = {}) {
  const fs = require('fs'); const path = require('path');
  const hasSupplied = Array.isArray(suppliedPhotos) && suppliedPhotos.length > 0;
  const MAX_ATTEMPTS = Math.max(1, parseInt(process.env.CONTENT_BUILD_ATTEMPTS || '2', 10));
  logger.info({ theme, slides, routine, maxAttempts: MAX_ATTEMPTS }, 'calendar: building carousel');

  let totalCost = 0;   // true $ across ALL attempts (API calls + design agent)
  let best = null;     // best attempt so far (passed, or fewest issues)
  // exclude — уже испробованные фото (при пересборке берём свежие); передаётся снаружи для студийной петли

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const scope = beginCost(); // sum every Claude API call this attempt makes
    // Число слайдов: если владелец прислал СВОИ фото — по их числу (кап 4 = шаблон).
    const nSlides = hasSupplied ? Math.min(suppliedPhotos.length, 4) : slides;
    let sel;
    if (hasSupplied) {
      // Фото владельца (локальные пути) — используем КАК ЕСТЬ, без авто-выбора и бэкапов.
      const loaded = [];
      for (const p of suppliedPhotos.slice(0, nSlides)) {
        try { loaded.push({ buffer: fs.readFileSync(p), name: path.basename(p), path: p }); }
        catch (e) { logger.warn({ p, e: e.message }, 'supplied photo read failed'); }
      }
      if (!loaded.length) throw new Error('присланные фото не читаются');
      sel = { photos: loaded, backups: [] };
    } else {
      sel = await photos.selectBest(nSlides, { folder, topic: theme, exclude });
      (sel.ranked || []).forEach((p) => exclude.push(p)); // never reuse on a rebuild
    }
    // Copy is written AFTER photo selection so slide bodies match the real
    // frames (tech-debt #0: «on the beam» под фото со стойкой на руках).
    // Catalog captions ride along on sel.photos; supplied photos have none →
    // generic copy as before. A targeted photo swap later can still drift from
    // the baked text — verify is the backstop there.
    const photoNotes = sel.photos.map((p) => p.caption ? `${p.caption}${p.subject ? ` [${p.subject}]` : ''}` : null);
    const plan = await generatePlan(theme, nSlides, photoNotes);
    const assembled = await assemble.assembleCarousel({
      topic: theme, photos: sel.photos, backups: sel.backups,
      cover: { headline: plan.cover.headline, cta: plan.cover.cta },
      inner: plan.inner, caption: plan.caption,
    });
    const buffers = assembled.slides.map((s) => s.buffer).filter(Boolean);
    // NB: do NOT pass the campaign brief (theme) into per-slide verify. The
    // verifier sees ONE slide at a time, so feeding it the whole brief makes it
    // flag every slide that doesn't repeat campaign facts (e.g. "slide 3 doesn't
    // mention Lagoona Mall") — a false positive that wastes a rebuild. Each slide
    // is judged on its OWN visual + text quality; brand identity only for context.
    const vr = await verifyCarousel(buffers, { context: 'AcroGym kids gymnastics & acrobatics — Instagram carousel' });

    // Targeted slide fix (owner rule 2026-07-03): when verification flags a
    // PHOTO on specific slides, swap just those photos in the SAME design and
    // re-verify — a full rebuild is the fallback, not the first response.
    const photoPathsArr = sel.photos.map((x) => x.path);
    if (!vr.ok && assembled.designId) {
      const usedPaths = new Set(photoPathsArr);
      let fresh = (sel.backups || []).filter((b) => b.faces_ok !== false && !usedPaths.has(b.path) && !exclude.includes(b.path));
      for (let i = 0; i < vr.slides.length; i++) {
        const sres = vr.slides[i];
        const slide = assembled.slides[i];
        if (sres.ok || !sres.photoRelated || !slide || !slide.bgElementId) continue;
        const fixed = await assemble.replaceSlidePhoto({
          designId: assembled.designId, page: slide.page, bgElementId: slide.bgElementId,
          candidates: fresh.filter((b) => !photos.nearDuplicate(b.path, photoPathsArr)).slice(0, 3),
        });
        if (!fixed) { logger.warn({ page: slide.page }, 'targeted slide fix: no candidate worked'); continue; }
        fresh = fresh.filter((b) => b.path !== fixed.path);
        usedPaths.add(fixed.path);
        totalCost += fixed.costUsd || 0;
        const recheck = await verifySlide(fixed.buffer, { context: `AcroGym kids gymnastics & acrobatics — Instagram carousel slide ${i + 1}/${assembled.slides.length}` });
        assembled.slides[i] = { ...slide, url: fixed.url, buffer: fixed.buffer };
        photoPathsArr[i] = fixed.path;
        vr.slides[i] = recheck;
        logger.info({ page: slide.page, photo: fixed.name, ok: recheck.ok }, 'targeted slide photo fix applied');
      }
      vr.ok = vr.slides.every((r) => r.ok) && vr.carousel.length === 0;
    }

    const cap = verifyCaption(assembled.caption);
    const apiCost = endCost(scope);
    totalCost += apiCost + (assembled.costUsd || 0); // API (copy+select+crop+verify) + design agent

    const issues = [
      ...vr.slides.flatMap((s, i) => s.issues.map((x) => `слайд ${i + 1}: ${x}`)),
      ...vr.carousel.map((x) => `карусель: ${x}`),
      ...cap.issues.map((x) => `подпись: ${x}`),
    ];
    if (assembled.overBudget) issues.push(`стоимость: дороже лимита ($${(assembled.costUsd || 0).toFixed(2)})`);
    const verifyOk = vr.ok && cap.ok && !assembled.overBudget;
    const cand = { assembled, issues, verifyOk, photoPaths: photoPathsArr };

    if (verifyOk) { best = cand; logger.info({ attempt }, 'self-check passed'); break; }
    if (!best || issues.length < best.issues.length) best = cand; // keep the cleanest attempt
    logger.warn({ attempt, issueCount: issues.length }, 'self-check found issues');
    if (attempt < MAX_ATTEMPTS) {
      await bot.sendMessage(ownerChatId,
        `🔍 Проверка нашла замечания — исправляю: пересобираю на других фото (попытка ${attempt + 1}/${MAX_ATTEMPTS})…`).catch(() => {});
    }
  }

  const { assembled, issues, verifyOk, photoPaths } = best;
  const draft = publish.newDraft({
    kind: 'post', igType: 'POST',
    caption: assembled.caption,
    slides: assembled.slides,
    theme, slidesCount: slides, // kept so 🔄 Rebuild can repeat the same brief
    photoPaths,                 // burned (recorded as used) only on actual publish
    routine: routine && verifyOk,
    verify: { ok: verifyOk, issues },
    costUsd: totalCost,
    source: `${routine ? 'calendar' : 'on-demand'}: ${theme}`,
  });

  if (assembled.overBudget) {
    await bot.sendMessage(ownerChatId,
      `⚠️ Пост собрался дороже лимита ($${(assembled.costUsd || 0).toFixed(2)} > $${agent.MAX_COST_USD}). Автопост отключён — проверь вручную.`).catch(() => {});
  }

  return draft;
}

// Собрать И запостить карточку утверждения — прежнее поведение (build + route).
async function buildAndRoute(bot, ownerChatId, opts = {}) {
  const draft = await buildDraft(bot, ownerChatId, opts);
  return publish.route(bot, ownerChatId, draft);
}

// Send a long markdown report to Telegram as plain-text chunks (TG cap ~4096).
async function sendChunked(bot, chatId, text, prefix = '') {
  const LIMIT = 3800;
  const body = (prefix ? prefix + '\n\n' : '') + String(text || '');
  for (let i = 0; i < body.length; i += LIMIT) {
    await bot.sendMessage(chatId, body.slice(i, i + LIMIT)).catch(() => {});
  }
}

/**
 * Run the autonomous competitor analysis and deliver the owner report to TG.
 * Used by the every-3-days cron AND the manual "🔎 Анализ сейчас" button.
 */
async function runResearchAndReport(bot, ownerChatId) {
  const lang = getPreferredLanguage(ownerChatId) === 'ru' ? 'ru' : 'en';
  const msg = lang === 'ru'
    ? { wait: '🔎 Провожу анализ конкурентов в Катаре… (1–3 мин)', fail: '⚠️ Анализ не удался: ', head: '📊 Анализ конкурентов', brief: ' · бриф планировщика обновлён ✅' }
    : { wait: '🔎 Running competitor analysis (Qatar)… (1–3 min)', fail: '⚠️ Analysis failed: ', head: '📊 Competitor analysis', brief: ' · planner brief updated ✅' };
  await bot.sendMessage(ownerChatId, msg.wait).catch(() => {});
  const res = await research.runAnalysis({ lang });
  if (!res.ok) {
    await bot.sendMessage(ownerChatId, `${msg.fail}${res.error}`).catch(() => {});
    return res;
  }
  await sendChunked(bot, ownerChatId, res.reportMd,
    `${msg.head} ${new Date().toLocaleDateString(lang === 'ru' ? 'ru-RU' : 'en-GB')}${res.briefUpdated ? msg.brief : ''}`);
  return res;
}

/** Start the cron schedules. Call once from index.js after the bot is up. */
function start(bot, ownerChatId, opts = {}) {
  const jobs = [];
  for (const item of PLAN) {
    const job = cron.schedule(item.cron, async () => {
      try {
        await buildAndRoute(bot, ownerChatId, { theme: item.theme, slides: item.slides, routine: item.routine });
      } catch (err) {
        logger.error({ err: err.message, name: item.name }, 'calendar job failed');
        await bot.sendMessage(ownerChatId, `⚠️ Автопост «${item.name}» не собрался: ${err.message}`).catch(() => {});
      }
    }, { timezone: TZ });
    jobs.push(job);
    logger.info({ name: item.name, cron: item.cron }, 'calendar job scheduled');
  }

  // Monthly photo-catalog refresh: picks up any NEW photos the owner added (the
  // builder is resume-safe — it only analyses paths not already catalogued, so
  // this is cheap unless lots were added). Runs as a detached child so it never
  // blocks or crashes the bot.
  const refresh = cron.schedule('30 4 1 * *', () => {
    try {
      const { spawn } = require('child_process');
      const script = require('path').join(__dirname, '../../scripts/build-photo-catalog.js');
      const out = require('fs').openSync(require('path').join(__dirname, '../../logs/catalog-refresh.log'), 'a');
      const child = spawn('node', [script], { detached: true, stdio: ['ignore', out, out] });
      child.unref();
      logger.info('photo-catalog monthly refresh started');
    } catch (err) { logger.error({ err: err.message }, 'catalog refresh spawn failed'); }
  }, { timezone: TZ });
  jobs.push(refresh);

  // Content-plan executor: DISABLED by owner design (19.07.2026). Approved-plan
  // posts are no longer built here DIRECTLY to the owner — on `plan:approve` the
  // themes are pushed to the studio queue (data/studio-week-queue.json) and the
  // content-studio daily cron (10:00) drips ONE/day through the critics' panel
  // review, then sends the final card to the owner's private content chat.
  // Building here too would double every post. Manual on-demand build still works
  // via the 📅 "▶️ Собрать следующий сейчас" button (plan:buildnext).

  // Autonomous competitor analysis every ~3 days (07:00). Runs on the claude.ai
  // subscription via the headless agent (NOT the metered API), refreshes the
  // planner's brief, and delivers the owner report to Telegram.
  const researchJob = cron.schedule('0 7 */3 * *', async () => {
    try { await runResearchAndReport(bot, ownerChatId); }
    catch (err) { logger.error({ err: err.message }, 'scheduled research failed'); }
  }, { timezone: TZ });
  jobs.push(researchJob);

  // Weekly auto-plan (Sunday 09:00): propose next week's plan from the FRESH
  // brief and send the owner a review card (he edits/approves; nothing publishes
  // without his tap). opts.proposePlan is provided by index.js (needs its UI).
  if (typeof opts.proposePlan === 'function') {
    const weeklyPlanJob = cron.schedule('0 9 * * 0', async () => {
      try { await opts.proposePlan(); }
      catch (err) { logger.error({ err: err.message }, 'weekly auto-plan failed'); }
    }, { timezone: TZ });
    jobs.push(weeklyPlanJob);
  }

  return jobs;
}

/**
 * Build a single content-plan item NOW (used by the "▶️ Собрать следующий" button).
 * Marks it built and routes an approval card. Returns the item or null if none due.
 */
async function buildNextPlanned(bot, ownerChatId) {
  const item = plan.nextPlanned();
  if (!item) return null;
  if (item.format === 'story') await buildStoryAndRoute(bot, ownerChatId, { theme: item.theme, routine: false });
  else await buildAndRoute(bot, ownerChatId, { theme: item.theme, slides: 4, routine: false });
  plan.setStatus(item.id, 'built');
  return item;
}

module.exports = { start, buildDraft, buildAndRoute, buildStoryAndRoute, buildReelAndRoute, buildNextPlanned, runResearchAndReport, generatePlan, pickPhotos, PLAN };
