'use strict';

/**
 * Content calendar + scheduler (Agent 4 — autonomous posting, Phase 3).
 *
 * Two entry paths, both ending in the publish.js hybrid gate:
 *   - SCHEDULED (cron): routine themes (e.g. weekly recap). routine=true → may
 *     auto-publish after self-verification.
 *   - ON-DEMAND (/post <topic>): routine=false → always an approval card.
 *
 * Visuals are assembled ONLY through Canva (assemble.js). Photos come from
 * Yandex.Disk /AcroGym/Marketing. Slide copy is generated by Claude as strict
 * JSON so the cover + inner slides are filled deterministically.
 */

const cron = require('node-cron');
const yandex = require('./yandex');
const photos = require('./photos');
const plan = require('./plan');
const research = require('./research');
const { getPreferredLanguage } = require('../../shared/preferences');
const assemble = require('./assemble');
const agent = require('./agent');
const publish = require('./publish');
const { verifyCarousel, verifySlide, verifyCaption } = require('./verify');
const { generateText, beginCost, endCost } = require('../../shared/claude');
const { createLogger } = require('../../shared/logger');

const logger = createLogger('content-bot');

const TZ = process.env.TIMEZONE || 'Asia/Qatar';

// Routine themes that may auto-publish. Cron in brand timezone.
// Conservative default: one weekly recap. Easy to extend.
// 🔴 routine=false EVERYWHERE until the visual pipeline is reliable (2026-06-28:
// agent filled the wrong layer → split photos; verify missed it). NOTHING
// auto-publishes — every scheduled build still goes to the owner for ✅.
const PLAN = [
  { name: 'weekly-recap', cron: '0 18 * * 4', theme: 'Weekly recap: highlights from training this week at AcroGym', slides: 4, routine: false },
];

const PLAN_SYSTEM = `You write Instagram carousel copy for AcroGym Qatar — a kids' gymnastics & acrobatics club in Doha. Audience: parents of children 3–14. Voice: warm, energetic, safe, professional. Output language: ENGLISH only.
Given a THEME and a slide count N, return STRICT JSON (no prose):
{"cover":{"headline":"<1-2 SHORT words only, ≤14 characters total — it must fit one line>","cta":"<short CTA, e.g. BOOK A TRIAL>"},
 "inner":[{"headline":"<ONE short word, uppercase, ≤11 chars>","body":"<1-2 sentences, <140 chars>"}, ... exactly N-1 items],
 "caption":"<full IG caption with 1-2 emojis and 6-8 relevant hashtags>"}
Keep it child-safe and on-brand. Never invent specific results or medical claims.`;

function parseJson(text) {
  try { const m = String(text).match(/\{[\s\S]*\}/); return m ? JSON.parse(m[0]) : null; } catch { return null; }
}

// Generate slide copy for a theme.
async function generatePlan(theme, slides = 4) {
  const raw = await generateText({
    system: PLAN_SYSTEM,
    user: `THEME: ${theme}\nN: ${slides}\nReturn the JSON.`,
    maxTokens: 900,
  });
  const plan = parseJson(raw);
  if (!plan || !plan.cover || !Array.isArray(plan.inner)) {
    throw new Error('plan generation: unparseable copy');
  }
  return plan;
}

// Pick N photos from Marketing (prefer a content folder, fall back to root).
async function pickPhotos(n, folder) {
  const candidates = [];
  const tryFolders = [folder, '/AcroGym/Marketing/AcroGym Competiton 2026', yandex.MARKETING].filter(Boolean);
  for (const f of tryFolders) {
    try {
      const imgs = await yandex.listImages(f, { limit: 200 });
      if (imgs.length) { candidates.push(...imgs); break; }
    } catch (err) { logger.warn({ folder: f, err: err.message }, 'pickPhotos: folder skip'); }
  }
  if (!candidates.length) throw new Error('no images found under /AcroGym/Marketing');
  // Shuffle then take n (deterministic enough; avoids always the same shots).
  for (let i = candidates.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [candidates[i], candidates[j]] = [candidates[j], candidates[i]]; }
  const chosen = candidates.slice(0, n);
  const photos = [];
  for (const c of chosen) {
    photos.push({ buffer: await yandex.downloadBuffer(c.path), name: c.name });
  }
  return photos;
}

// Copy for a single Instagram STORY (9:16): short headline + CTA + caption.
const STORY_SYSTEM = `You write copy for ONE Instagram STORY (9:16 vertical) for AcroGym Qatar — a kids' gymnastics & acrobatics club in Doha. Audience: parents of children 3–14. English only. Voice: warm, energetic, safe.
Given a TOPIC, return STRICT JSON (no prose):
{"headline":"<1-2 SHORT punchy words, ≤12 characters total, MUST fit one line — e.g. \\"WE'RE OPEN\\", \\"NEW GYM\\", \\"SOON\\">","cta":"<short CTA, e.g. BOOK A TRIAL>","caption":"<short IG caption, 1-2 emojis, 3-6 hashtags>"}
Keep it child-safe and on-brand. Never invent prices, dates, or results.`;

async function generateStoryCopy(theme) {
  const raw = await generateText({ system: STORY_SYSTEM, user: `TOPIC: ${theme}\nReturn the JSON.`, maxTokens: 400 });
  const c = parseJson(raw);
  if (!c || !c.headline) throw new Error('story copy: unparseable');
  return { headline: c.headline, cta: c.cta || 'BOOK A TRIAL', caption: c.caption || '' };
}

/**
 * Build a single 9:16 STORY end-to-end and route it through the gate.
 * Mirrors buildAndRoute (auto-fix attempts, true cost, approval card) for stories.
 */
async function buildStoryAndRoute(bot, ownerChatId, { theme, routine = false, folder } = {}) {
  const MAX_ATTEMPTS = Math.max(1, parseInt(process.env.CONTENT_BUILD_ATTEMPTS || '2', 10));
  logger.info({ theme, routine, maxAttempts: MAX_ATTEMPTS }, 'calendar: building story');

  let totalCost = 0; let best = null; const exclude = [];
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const scope = beginCost();
    const copy = await generateStoryCopy(theme);
    const sel = await photos.selectBest(1, { folder, topic: theme, exclude, story: true });
    (sel.ranked || []).forEach((p) => exclude.push(p));
    const photo = sel.photos && sel.photos[0];
    if (!photo) throw new Error('story: no photo selected');
    const assembled = await assemble.assembleStory({ topic: theme, photo, headline: copy.headline, cta: copy.cta, caption: copy.caption });
    const buf = assembled.slides[0] && assembled.slides[0].buffer;
    const vr = buf
      ? await verifySlide(buf, {
          context: 'AcroGym kids gymnastics & acrobatics — single Instagram story 9:16 (cover-style: hook headline + asterisk + CTA pill)',
          expectedRatio: 1080 / 1920, ratioLabel: '9:16',
        })
      : { ok: false, issues: ['нет изображения сторис'] };
    const cap = verifyCaption(assembled.caption);
    const apiCost = endCost(scope);
    totalCost += apiCost + (assembled.costUsd || 0);

    const issues = [...vr.issues.map((x) => `сторис: ${x}`), ...cap.issues.map((x) => `подпись: ${x}`)];
    if (assembled.overBudget) issues.push(`стоимость: дороже лимита ($${(assembled.costUsd || 0).toFixed(2)})`);
    const verifyOk = vr.ok && cap.ok && !assembled.overBudget;
    const cand = { assembled, issues, verifyOk };
    if (verifyOk) { best = cand; logger.info({ attempt }, 'story self-check passed'); break; }
    if (!best || issues.length < best.issues.length) best = cand;
    logger.warn({ attempt, issueCount: issues.length }, 'story self-check found issues');
    if (attempt < MAX_ATTEMPTS) {
      await bot.sendMessage(ownerChatId, `🔍 Проверка нашла замечания по сторис — пересобираю на другом фото (попытка ${attempt + 1}/${MAX_ATTEMPTS})…`).catch(() => {});
    }
  }

  const { assembled, issues, verifyOk } = best;
  const draft = publish.newDraft({
    kind: 'story', igType: 'STORY',
    caption: assembled.caption, slides: assembled.slides,
    theme, slidesCount: 1, storyFormat: true,
    routine: routine && verifyOk,
    verify: { ok: verifyOk, issues },
    costUsd: totalCost,
    source: `${routine ? 'calendar' : 'on-demand'} story: ${theme}`,
  });
  return publish.route(bot, ownerChatId, draft);
}

/**
 * Build a 9:16 REEL (branded frame + gentle Ken-Burns motion → MP4) and deliver
 * it to the owner as a Telegram video. 🔴 Reels are NOT auto-published yet: the
 * MP4 is generated locally (no public URL for Metricool), so for now it's a
 * preview the owner downloads/posts. Auto-publish needs a hosting decision.
 */
async function buildReelAndRoute(bot, ownerChatId, { theme, folder } = {}) {
  logger.info({ theme }, 'calendar: building reel');
  const scope = beginCost();
  const copy = await generateStoryCopy(theme);
  const sel = await photos.selectBest(1, { folder, topic: theme, exclude: [], story: true });
  const photo = sel.photos && sel.photos[0];
  if (!photo) throw new Error('reel: no photo selected');
  const assembled = await assemble.assembleReel({ topic: theme, photo, headline: copy.headline, cta: copy.cta, caption: copy.caption });
  const poster = assembled.slides[0] && assembled.slides[0].poster;
  const mp4 = assembled.slides[0] && assembled.slides[0].buffer;
  const vr = poster
    ? await verifySlide(poster, { context: 'AcroGym story/reel 9:16 cover-style frame', expectedRatio: 1080 / 1920, ratioLabel: '9:16' })
    : { ok: true, issues: [] };
  const cap = verifyCaption(assembled.caption);
  const apiCost = endCost(scope);
  const totalCost = apiCost + (assembled.costUsd || 0);

  const issues = [...vr.issues.map((x) => `кадр: ${x}`), ...cap.issues.map((x) => `подпись: ${x}`)];
  const verifyLine = issues.length ? `⚠️ Замечания:\n• ${issues.join('\n• ')}` : '✅ Самопроверка пройдена';
  const note = `🎬 <b>Reel (9:16, движение)</b> — <i>${escapeHtmlSafe(theme)}</i>\n💰 ~$${totalCost.toFixed(2)}\n${verifyLine}\n\n<i>Авто-публикация Reels пока не подключена — скачай и выложи, либо подключим хостинг видео.</i>`;
  try {
    await bot.sendVideo(ownerChatId, mp4, { caption: note, parse_mode: 'HTML' }, { filename: 'acrogym-reel.mp4', contentType: 'video/mp4' });
  } catch (err) {
    logger.error({ err: err.message }, 'reel sendVideo failed');
    await bot.sendMessage(ownerChatId, '⚠️ Reel собрался, но не отправился: ' + err.message).catch(() => {});
  }
  // Caption to copy separately (Telegram video captions can't be long/selectable).
  await bot.sendMessage(ownerChatId, `<pre>${escapeHtmlSafe(assembled.caption || '')}</pre>`, { parse_mode: 'HTML' }).catch(() => {});
  return { ok: true, costUsd: totalCost, issues };
}

function escapeHtmlSafe(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/**
 * Build a themed carousel end-to-end and route it through the gate.
 * @param {object} bot Telegram bot
 * @param {string|number} ownerChatId
 * @param {object} opts { theme, slides, routine, folder }
 */
async function buildAndRoute(bot, ownerChatId, { theme, slides = 4, routine = false, folder } = {}) {
  const MAX_ATTEMPTS = Math.max(1, parseInt(process.env.CONTENT_BUILD_ATTEMPTS || '2', 10));
  logger.info({ theme, slides, routine, maxAttempts: MAX_ATTEMPTS }, 'calendar: building carousel');

  let totalCost = 0;   // true $ across ALL attempts (API calls + design agent)
  let best = null;     // best attempt so far (passed, or fewest issues)
  const exclude = [];  // photos already tried — auto-rebuild picks fresh ones

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const scope = beginCost(); // sum every Claude API call this attempt makes
    const plan = await generatePlan(theme, slides);
    const sel = await photos.selectBest(slides, { folder, topic: theme, exclude });
    (sel.ranked || []).forEach((p) => exclude.push(p)); // never reuse on a rebuild
    const assembled = await assemble.assembleCarousel({
      topic: theme, photos: sel.photos,
      cover: { headline: plan.cover.headline, cta: plan.cover.cta },
      inner: plan.inner, caption: plan.caption,
    });
    const buffers = assembled.slides.map((s) => s.buffer).filter(Boolean);
    // NB: do NOT pass the campaign brief (theme) into per-slide verify. The
    // verifier sees ONE slide at a time, so feeding it the whole brief makes it
    // flag every slide that doesn't repeat campaign facts (e.g. "slide 3 doesn't
    // mention Lagoona Mall") — a false positive that wastes a rebuild. Each slide
    // is judged on its OWN visual + text quality; brand identity only for context.
    const vr = await verifyCarousel(buffers, { context: 'AcroGym kids gymnastics & acrobatics — Instagram carousel' });
    const cap = verifyCaption(assembled.caption);
    const apiCost = endCost(scope);
    totalCost += apiCost + (assembled.costUsd || 0); // API (copy+select+crop+verify) + design agent

    const issues = [
      ...vr.slides.flatMap((s, i) => s.issues.map((x) => `слайд ${i + 1}: ${x}`)),
      ...vr.carousel.map((x) => `карусель: ${x}`),
      ...cap.issues.map((x) => `подпись: ${x}`),
    ];
    if (assembled.overBudget) issues.push(`стоимость: дороже лимита ($${(assembled.costUsd || 0).toFixed(2)})`);
    const verifyOk = vr.ok && cap.ok && !assembled.overBudget;
    const cand = { assembled, issues, verifyOk };

    if (verifyOk) { best = cand; logger.info({ attempt }, 'self-check passed'); break; }
    if (!best || issues.length < best.issues.length) best = cand; // keep the cleanest attempt
    logger.warn({ attempt, issueCount: issues.length }, 'self-check found issues');
    if (attempt < MAX_ATTEMPTS) {
      await bot.sendMessage(ownerChatId,
        `🔍 Проверка нашла замечания — исправляю: пересобираю на других фото (попытка ${attempt + 1}/${MAX_ATTEMPTS})…`).catch(() => {});
    }
  }

  const { assembled, issues, verifyOk } = best;
  const draft = publish.newDraft({
    kind: 'post', igType: 'POST',
    caption: assembled.caption,
    slides: assembled.slides,
    theme, slidesCount: slides, // kept so 🔄 Rebuild can repeat the same brief
    routine: routine && verifyOk,
    verify: { ok: verifyOk, issues },
    costUsd: totalCost,
    source: `${routine ? 'calendar' : 'on-demand'}: ${theme}`,
  });

  if (assembled.overBudget) {
    await bot.sendMessage(ownerChatId,
      `⚠️ Пост собрался дороже лимита ($${(assembled.costUsd || 0).toFixed(2)} > $${agent.MAX_COST_USD}). Автопост отключён — проверь вручную.`).catch(() => {});
  }

  return publish.route(bot, ownerChatId, draft);
}

// Send a long markdown report to Telegram as plain-text chunks (TG cap ~4096).
async function sendChunked(bot, chatId, text, prefix = '') {
  const LIMIT = 3800;
  const body = (prefix ? prefix + '\n\n' : '') + String(text || '');
  for (let i = 0; i < body.length; i += LIMIT) {
    await bot.sendMessage(chatId, body.slice(i, i + LIMIT)).catch(() => {});
  }
}

/**
 * Run the autonomous competitor analysis and deliver the owner report to TG.
 * Used by the every-3-days cron AND the manual "🔎 Анализ сейчас" button.
 */
async function runResearchAndReport(bot, ownerChatId) {
  const lang = getPreferredLanguage(ownerChatId) === 'ru' ? 'ru' : 'en';
  const msg = lang === 'ru'
    ? { wait: '🔎 Провожу анализ конкурентов в Катаре… (1–3 мин)', fail: '⚠️ Анализ не удался: ', head: '📊 Анализ конкурентов', brief: ' · бриф планировщика обновлён ✅' }
    : { wait: '🔎 Running competitor analysis (Qatar)… (1–3 min)', fail: '⚠️ Analysis failed: ', head: '📊 Competitor analysis', brief: ' · planner brief updated ✅' };
  await bot.sendMessage(ownerChatId, msg.wait).catch(() => {});
  const res = await research.runAnalysis({ lang });
  if (!res.ok) {
    await bot.sendMessage(ownerChatId, `${msg.fail}${res.error}`).catch(() => {});
    return res;
  }
  await sendChunked(bot, ownerChatId, res.reportMd,
    `${msg.head} ${new Date().toLocaleDateString(lang === 'ru' ? 'ru-RU' : 'en-GB')}${res.briefUpdated ? msg.brief : ''}`);
  return res;
}

/** Start the cron schedules. Call once from index.js after the bot is up. */
function start(bot, ownerChatId, opts = {}) {
  const jobs = [];
  for (const item of PLAN) {
    const job = cron.schedule(item.cron, async () => {
      try {
        await buildAndRoute(bot, ownerChatId, { theme: item.theme, slides: item.slides, routine: item.routine });
      } catch (err) {
        logger.error({ err: err.message, name: item.name }, 'calendar job failed');
        await bot.sendMessage(ownerChatId, `⚠️ Автопост «${item.name}» не собрался: ${err.message}`).catch(() => {});
      }
    }, { timezone: TZ });
    jobs.push(job);
    logger.info({ name: item.name, cron: item.cron }, 'calendar job scheduled');
  }

  // Monthly photo-catalog refresh: picks up any NEW photos the owner added (the
  // builder is resume-safe — it only analyses paths not already catalogued, so
  // this is cheap unless lots were added). Runs as a detached child so it never
  // blocks or crashes the bot.
  const refresh = cron.schedule('30 4 1 * *', () => {
    try {
      const { spawn } = require('child_process');
      const script = require('path').join(__dirname, '../../scripts/build-photo-catalog.js');
      const out = require('fs').openSync(require('path').join(__dirname, '../../logs/catalog-refresh.log'), 'a');
      const child = spawn('node', [script], { detached: true, stdio: ['ignore', out, out] });
      child.unref();
      logger.info('photo-catalog monthly refresh started');
    } catch (err) { logger.error({ err: err.message }, 'catalog refresh spawn failed'); }
  }, { timezone: TZ });
  jobs.push(refresh);

  // Content-plan executor: every morning, build the post(s) the owner's APPROVED
  // plan scheduled for today and send each as an approval card (routine=false →
  // nothing auto-publishes; the owner taps "🕒 В лучшее время"). The plan is
  // owner-driven and only ever decides WHAT to assemble today.
  const planJob = cron.schedule('0 8 * * *', async () => {
    let due;
    try { due = plan.dueToday(); } catch (err) { logger.error({ err: err.message }, 'plan dueToday failed'); return; }
    if (!due.length) return;
    logger.info({ count: due.length }, 'content-plan: building today\'s posts');
    for (const item of due) {
      try {
        const isStory = item.format === 'story';
        await bot.sendMessage(ownerChatId, `📅 По плану на сегодня (${isStory ? '📱 сторис' : '📸 пост'}): «${item.theme}» — собираю…`).catch(() => {});
        if (isStory) await buildStoryAndRoute(bot, ownerChatId, { theme: item.theme, routine: false });
        else await buildAndRoute(bot, ownerChatId, { theme: item.theme, slides: 4, routine: false });
        plan.setStatus(item.id, 'built'); // don't rebuild tomorrow; owner still gates publish
      } catch (err) {
        logger.error({ err: err.message, theme: item.theme }, 'plan post build failed');
        await bot.sendMessage(ownerChatId, `⚠️ Пост по плану «${item.theme}» не собрался: ${err.message}`).catch(() => {});
      }
    }
  }, { timezone: TZ });
  jobs.push(planJob);

  // Autonomous competitor analysis every ~3 days (07:00). Runs on the claude.ai
  // subscription via the headless agent (NOT the metered API), refreshes the
  // planner's brief, and delivers the owner report to Telegram.
  const researchJob = cron.schedule('0 7 */3 * *', async () => {
    try { await runResearchAndReport(bot, ownerChatId); }
    catch (err) { logger.error({ err: err.message }, 'scheduled research failed'); }
  }, { timezone: TZ });
  jobs.push(researchJob);

  // Weekly auto-plan (Sunday 09:00): propose next week's plan from the FRESH
  // brief and send the owner a review card (he edits/approves; nothing publishes
  // without his tap). opts.proposePlan is provided by index.js (needs its UI).
  if (typeof opts.proposePlan === 'function') {
    const weeklyPlanJob = cron.schedule('0 9 * * 0', async () => {
      try { await opts.proposePlan(); }
      catch (err) { logger.error({ err: err.message }, 'weekly auto-plan failed'); }
    }, { timezone: TZ });
    jobs.push(weeklyPlanJob);
  }

  return jobs;
}

/**
 * Build a single content-plan item NOW (used by the "▶️ Собрать следующий" button).
 * Marks it built and routes an approval card. Returns the item or null if none due.
 */
async function buildNextPlanned(bot, ownerChatId) {
  const item = plan.nextPlanned();
  if (!item) return null;
  if (item.format === 'story') await buildStoryAndRoute(bot, ownerChatId, { theme: item.theme, routine: false });
  else await buildAndRoute(bot, ownerChatId, { theme: item.theme, slides: 4, routine: false });
  plan.setStatus(item.id, 'built');
  return item;
}

module.exports = { start, buildAndRoute, buildStoryAndRoute, buildReelAndRoute, buildNextPlanned, runResearchAndReport, generatePlan, pickPhotos, PLAN };
